-- Insert Fake Customers
INSERT INTO Customers VALUES (1000,'Nilsen', 'Johan', '688 Taco Dr', 'FakeUser1','FakeUser');
INSERT INTO Customers VALUES (1001,'Bob', 'Bodet', '228 Bell Dr', 'FakeUser2','FakeUser');
INSERT INTO Customers VALUES (1002,'Jim', 'Hannagan', '6148 10th Street', 'FakeUser3','FakeUser');
INSERT INTO Customers VALUES (1003,'Daren', 'Nealson', '6768 Elask Dr', 'FakeUser4','FakeUser');
INSERT INTO Customers VALUES (1004,'Joe', 'Price', '6543 Keystone Dr', 'FakeUser5','FakeUser');
INSERT INTO Customers VALUES (1005,'Kim', 'Possible', '9688 Poncho Ct', 'FakeUser6','FakeUser');
INSERT INTO Customers VALUES (1006,'Micky', 'Mouse', '1688 Beamer Dr', 'FakeUser7','FakeUser');
INSERT INTO Customers VALUES (1007,'Dale', 'Johnson', '3688 Wombat Dr', 'FakeUser8','FakeUser');
INSERT INTO Customers VALUES (1008,'Tucker', 'Evil', '6858 B-Rice Blvd', 'FakeUser9','FakeUser');
INSERT INTO Customers VALUES (1009,'Bobby', 'Earny', '6848 Doormat Dr', 'FakeUser10','FakeUser');
INSERT INTO Customers VALUES (1010,'Archer', 'Comeda', '981 Airplane Dr', 'FakeUser11','FakeUser');
-- Insert Cars Statements
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Saint Louis','23-Apr-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Saint Louis','24-Apr-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Saint Louis','25-Apr-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Saint Louis','26-Apr-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Kansas','27-Nov-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Kansas','28-Nov-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Kansas','29-Nov-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Kansas','30-Nov-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Kansas','01-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Columbia','01-Jun-12','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Columbia','02-Jun-12','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Columbia','03-Jun-12','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Columbia','04-Jun-12','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Columbia','05-Jun-12','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Boston','06-Jan-12','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Boston','07-Jan-12','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Boston','08-Jan-12','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Boston','09-Jan-12','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Boston','10-Jan-12','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2','Pafawag','Miami','11-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX3','Pafawag','Miami','12-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX4','Pafawag','Miami','13-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX5','Pafawag','Miami','14-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX6','Pafawag','Miami','15-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX7','Pafawag','Miami','16-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-1','Baldwin','Chicago','17-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-2','Baldwin','Chicago','18-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-3','Baldwin','Chicago','19-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4','Baldwin','Chicago','20-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-5','Baldwin','Chicago','21-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-6','Baldwin','Chicago','22-Nov-11','Chemical Tank', '1.3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','03-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','04-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','05-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','06-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','07-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Seattle','08-Feb-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','03-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','04-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','05-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','06-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','07-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','08-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','09-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','10-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Tacoma','11-Mar-12','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','27-Apr-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','28-Apr-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','29-Apr-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','30-Apr-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','01-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','02-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','03-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','04-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','05-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','06-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','07-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','08-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Duluth','09-May-12','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','01-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','02-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','03-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','04-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','05-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','06-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','07-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','08-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('AXO-ZB','Alstom','Toledo','09-Jun-11','coal car', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','06-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','07-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','08-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','09-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','10-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','11-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','12-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','13-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','14-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','15-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','16-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('CXTRX','Fablok','Philadelphia','17-Oct-11','Hopper', '4.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','28-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','29-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','30-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','31-Dec-11','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','01-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','02-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','03-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','04-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','05-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','06-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','07-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('JH-ZX2A','Pafawag','San Diego','08-Jan-12','Flat bed', '6');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','20-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','21-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','22-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','23-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','24-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','25-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','26-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','27-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('XZ-4E','Baldwin','Baltimore','28-Nov-11','Chemical Tank', '3');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','03-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','04-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','05-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','06-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','07-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','08-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','09-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','10-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','11-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','12-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','13-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('SE-56B','Siemens','Pittsburgh','14-Apr-12','Boxcar', '2.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','06-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','07-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','08-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','09-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','10-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('HO-1B','Ford','Portland','11-Dec-11','Boxcar', '1.1');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','12-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','30-Nov-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','01-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','02-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','03-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','04-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','05-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','06-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','07-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','08-Dec-11','grain car', '2.2');
Insert into Cars (Model,Manufacturer,Location,ServiceDate,Type, MaxWeight) VALUES ('GO-1BC','Alco','Savannah','09-Dec-11','grain car', '2.2');